from sqlalchemy import Column, Integer, String, Float, Text
from app.db.database import Base

class Product(Base):
    __tablename__ = "products"

    id = Column(Integer, primary_key=True, index=True)
    sku = Column(String, nullable=True)
    style_number = Column(String, nullable=True)
    style_name = Column(String, nullable=True)
    customer_group_description = Column(String, nullable=True)
    brand_description = Column(String, nullable=True)
    collection_name = Column(String, nullable=True)
    dye_method = Column(String, nullable=True)
    dye_method_description = Column(String, nullable=True)
    surface_finish_description = Column(String, nullable=True)
    gauge = Column(String, nullable=True)
    fiber_brand_category = Column(String, nullable=True)
    pattern_type = Column(String, nullable=True)
    pattern_scale = Column(String, nullable=True)
    budget_category = Column(String, nullable=True)
    stain_resistance = Column(String, nullable=True)
    gsa_stain_release = Column(String, nullable=True)
    flammability = Column(String, nullable=True)
    smoke_density = Column(String, nullable=True)
    static_propensity = Column(String, nullable=True)
    fiber_brand_code = Column(String, nullable=True)
    fiber_brand_description = Column(String, nullable=True)
    style_code = Column(String, nullable=True)
    product_group = Column(String, nullable=True)
    product_subgroup = Column(String, nullable=True)
    fiber_content_description = Column(String, nullable=True)
    producttype = Column(String, nullable=True)
    primarymarket = Column(String, nullable=True)
    secondarymarket = Column(String, nullable=True)
    overallthickness = Column(String, nullable=True)
    constructiontype = Column(String, nullable=True)
    min_sq_yard = Column(String, nullable=True)
    segment = Column(String, nullable=True)
    stylewarranty1 = Column(String, nullable=True)
    stylewarranty2 = Column(String, nullable=True)
    stylewarranty3 = Column(String, nullable=True)
    stylewarranty4 = Column(String, nullable=True)
    stylewarranty5 = Column(String, nullable=True)
    procurement = Column(String, nullable=True)
    construction_category = Column(String, nullable=True)
    overview = Column(Text, nullable=True)
    sellingstylebulletcontent1 = Column(String, nullable=True)
    sellingstylebulletcontent2 = Column(String, nullable=True)
    sellingstylebulletcontent3 = Column(String, nullable=True)
    sellingstylebulletcontent4 = Column(String, nullable=True)
    sellingstylebulletcontent5 = Column(String, nullable=True)
    sellingstylebulletcontent6 = Column(String, nullable=True)
    sellingstylegreenlabelnumber = Column(String, nullable=True)
    countryoforigin = Column(String, nullable=True)
    resistancetochemicals = Column(String, nullable=True)
    resistancetolight = Column(String, nullable=True)
    resistancetoheat = Column(String, nullable=True)
    criticalradientflux = Column(String, nullable=True)
    fireresistance = Column(String, nullable=True)
    flamespread = Column(String, nullable=True)
    resilientwallbasestandard = Column(String, nullable=True)
    style_classification = Column(String, nullable=True)
    floorscore = Column(String, nullable=True)
    wear_layer = Column(String, nullable=True)
    finish = Column(String, nullable=True)
    surface_profile = Column(String, nullable=True)
    recommended_adhesive = Column(String, nullable=True)
    static_load = Column(String, nullable=True)
    squareness = Column(String, nullable=True)
    thickness = Column(String, nullable=True)
    size_and_tolerance = Column(String, nullable=True)
    flexibility = Column(String, nullable=True)
    dimensional_stability = Column(String, nullable=True)
    residual_indentation = Column(String, nullable=True)
    static_coefficient_of_friction = Column(String, nullable=True)
    totalrecycledcontent = Column(Float, nullable=True)
    virginvinyl = Column(String, nullable=True)
    certification_detail = Column(String, nullable=True)
    embodied_carbon = Column(Float, nullable=True)
    beyond_carbon_neutral = Column(Float, nullable=True)
    installationmethod = Column(String, nullable=True)
    csi_master_formatname = Column(String, nullable=True)
    csi_master_formatnumber = Column(String, nullable=True)
    edge_treatment = Column(String, nullable=True)
    environmentalproductdeclaration = Column(String, nullable=True)
    soil_release_technology = Column(String, nullable=True)
    protective_finishes = Column(String, nullable=True)
    carbon_handprint = Column(Float, nullable=True)
    material_health = Column(String, nullable=True)
    mindclick_rating = Column(String, nullable=True)
    commercial_initiative = Column(String, nullable=True)
    warranty_link = Column(String, nullable=True)
    installation_link = Column(String, nullable=True)
    care_link = Column(String, nullable=True)
    install_method = Column(String, nullable=True)
    color_code = Column(String, nullable=True)
    marketing_color_name = Column(String, nullable=True)
    color_name = Column(String, nullable=True)
    size = Column(String, nullable=True)
    size_description = Column(String, nullable=True)
    backing_code = Column(String, nullable=True)
    backing_description = Column(String, nullable=True)
    marketing_product_group = Column(String, nullable=True)
    dropped = Column(String, nullable=True)
    deleted = Column(String, nullable=True)
    introduction_date = Column(String, nullable=True)
    quickship = Column(String, nullable=True)
    finished_pile_thickness = Column(String, nullable=True)
    alternatestylenumber1 = Column(String, nullable=True)
    alternatestylecolor1 = Column(String, nullable=True)
    alternatestylenumber2 = Column(String, nullable=True)
    alternatestylecolor2 = Column(String, nullable=True)
    alternatestylenumber3 = Column(String, nullable=True)
    alternatestylecolor3 = Column(String, nullable=True)
    alternatestylenumber4 = Column(String, nullable=True)
    alternatestylecolor4 = Column(String, nullable=True)
    alternatestylenumber5 = Column(String, nullable=True)
    alternatestylecolor5 = Column(String, nullable=True)
    alternatestylenumber6 = Column(String, nullable=True)
    alternatestylecolor6 = Column(String, nullable=True)
    alternatestylenumber7 = Column(String, nullable=True)
    alternatestylecolor7 = Column(String, nullable=True)
    alternatestylenumber8 = Column(String, nullable=True)
    alternatestylecolor8 = Column(String, nullable=True)
    alternatestylenumber9 = Column(String, nullable=True)
    alternatestylecolor9 = Column(String, nullable=True)
    alternatestylenumber10 = Column(String, nullable=True)
    alternatestylecolor10 = Column(String, nullable=True)
    alternatestylenumbercolorimage1 = Column(String, nullable=True)
    alternatestylenumbercolorimage2 = Column(String, nullable=True)
    alternatestylenumbercolorimage3 = Column(String, nullable=True)
    alternatestylenumbercolorimage4 = Column(String, nullable=True)
    alternatestylenumbercolorimage5 = Column(String, nullable=True)
    alternatestylenumbercolorimage6 = Column(String, nullable=True)
    alternatestylenumbercolorimage7 = Column(String, nullable=True)
    alternatestylenumbercolorimage8 = Column(String, nullable=True)
    alternatestylenumbercolorimage9 = Column(String, nullable=True)
    alternatestylenumbercolorimage10 = Column(String, nullable=True)
    online_sample_available = Column(String, nullable=True)
    environmental_claims_validation = Column(Float, nullable=True)
    tarr = Column(String, nullable=True)
    health_product_declaration = Column(String, nullable=True)
    leed_certification = Column(String, nullable=True)
    ns140 = Column(String, nullable=True)
    red_list_free = Column(String, nullable=True)
    living_product_challenge = Column(String, nullable=True)
    take_back_program = Column(String, nullable=True)
    tvoc_range = Column(String, nullable=True)
    mindful_materials = Column(String, nullable=True)
    upc_code = Column(Float, nullable=True)
    msrp = Column(Float, nullable=True)
    master_number = Column(String, nullable=True)
    master_name = Column(String, nullable=True)
    sales_available = Column(String, nullable=True)
    product_family = Column(String, nullable=True)
    allow_sales_flag = Column(String, nullable=True)
    preorder_flag = Column(String, nullable=True)
    product_classification = Column(String, nullable=True)
    display_name = Column(String, nullable=True)
    display_desc = Column(String, nullable=True)
    declarelabel = Column(String, nullable=True)
    readytoship = Column(String, nullable=True)
    inv_sku = Column(String, nullable=True)
    width = Column(Float, nullable=True)
    width_ft = Column(Float, nullable=True)
    weight = Column(Float, nullable=True)
    size_number = Column(String, nullable=True)
    inv_backing_code = Column(String, nullable=True)
    primary_backing = Column(String, nullable=True)
    secondary_backing = Column(String, nullable=True)
    sqft_per_piece = Column(Float, nullable=True)
    sqft_per_carton = Column(Float, nullable=True)
    product_avail_readytoship = Column(String, nullable=True)
    product_avail_readytoship_west = Column(String, nullable=True)
    product_avail_quickship = Column(String, nullable=True)
    pounds_per_carton = Column(Float, nullable=True)
    color_family = Column(String, nullable=True)
    uom = Column(String, nullable=True)
    pricing_uom = Column(String, nullable=True)
    max_rollsize = Column(Float, nullable=True)
    custom_product = Column(String, nullable=True)
    cartons_per_pallet = Column(Float, nullable=True)
    color_number = Column(String, nullable=True)
    inventory_color_name = Column(String, nullable=True)
    product_typename = Column(String, nullable=True)
    inv_product_group = Column(String, nullable=True)
    std_roll_length = Column(Float, nullable=True)
    yrd_per_roll = Column(Float, nullable=True)
    face_weight = Column(String, nullable=True)
    erp_product_category = Column(String, nullable=True)
    inv_sku_product_classification = Column(String, nullable=True)
    inv_sku_display_name = Column(String, nullable=True)
    inv_sku_display_desc = Column(String, nullable=True)
    pattern_number = Column(String, nullable=True)
    inventory_sku_length = Column(Float, nullable=True)
    pieces_per_carton = Column(Float, nullable=True)
    light_refectancy = Column(Float, nullable=True)
    construction = Column(String, nullable=True)
    surface_finishcode = Column(String, nullable=True)
    pile_weight = Column(String, nullable=True)
    total_weight = Column(Float, nullable=True)
    weight_density = Column(String, nullable=True)
    stiches_per_inch = Column(String, nullable=True)
    total_thickness = Column(String, nullable=True)
    pattern_repeat = Column(String, nullable=True)
    pattern_repeat_width = Column(String, nullable=True)
    pattern_repeat_length = Column(String, nullable=True)
    durability_rating = Column(Float, nullable=True)
    indoor_air_quality = Column(String, nullable=True)
    inventory_style_name = Column(String, nullable=True)
    inv_product_classification = Column(String, nullable=True)
    inv_style_code = Column(String, nullable=True)
    availablesizes = Column(String, nullable=True)
    edgetreatmentlistforrugs = Column(String, nullable=True)
    thumb_image = Column(String, nullable=True)
    roomscene = Column(String, nullable=True)
    specsheet = Column(String, nullable=True)
    collectionbrochure = Column(String, nullable=True)
    warranty = Column(String, nullable=True)
    careandmaintenance = Column(String, nullable=True)
    installation = Column(String, nullable=True)
    available_sizes = Column(String, nullable=True)
    rug_edge_treatment = Column(String, nullable=True)
    installation_pattern = Column(String, nullable=True)
    specify_for_a_cure = Column(String, nullable=True)
    the_waterways_project = Column(String, nullable=True)


from pydantic import BaseModel
from typing import Optional

class ProductSchema(BaseModel):
    sku: Optional[str] = None
    style_number: Optional[str] = None
    style_name: Optional[str] = None
    customer_group_description: Optional[str] = None
    brand_description: Optional[str] = None
    collection_name: Optional[str] = None
    dye_method: Optional[str] = None
    dye_method_description: Optional[str] = None
    surface_finish_description: Optional[str] = None
    gauge: Optional[str] = None
    fiber_brand_category: Optional[str] = None
    pattern_type: Optional[str] = None
    pattern_scale: Optional[str] = None
    budget_category: Optional[str] = None
    stain_resistance: Optional[str] = None
    gsa_stain_release: Optional[str] = None
    flammability: Optional[str] = None
    smoke_density: Optional[str] = None
    static_propensity: Optional[str] = None
    fiber_brand_code: Optional[str] = None
    fiber_brand_description: Optional[str] = None
    style_code: Optional[str] = None
    product_group: Optional[str] = None
    product_subgroup: Optional[str] = None
    fiber_content_description: Optional[str] = None
    producttype: Optional[str] = None
    primarymarket: Optional[str] = None
    secondarymarket: Optional[str] = None
    overallthickness: Optional[str] = None
    constructiontype: Optional[str] = None
    min_sq_yard: Optional[str] = None
    segment: Optional[str] = None
    stylewarranty1: Optional[str] = None
    stylewarranty2: Optional[str] = None
    stylewarranty3: Optional[str] = None
    stylewarranty4: Optional[str] = None
    stylewarranty5: Optional[str] = None
    procurement: Optional[str] = None
    construction_category: Optional[str] = None
    overview: Optional[str] = None
    sellingstylebulletcontent1: Optional[str] = None
    sellingstylebulletcontent2: Optional[str] = None
    sellingstylebulletcontent3: Optional[str] = None
    sellingstylebulletcontent4: Optional[str] = None
    sellingstylebulletcontent5: Optional[str] = None
    sellingstylebulletcontent6: Optional[str] = None
    sellingstylegreenlabelnumber: Optional[str] = None
    countryoforigin: Optional[str] = None
    resistancetochemicals: Optional[str] = None
    resistancetolight: Optional[str] = None
    resistancetoheat: Optional[str] = None
    criticalradientflux: Optional[str] = None
    fireresistance: Optional[str] = None
    flamespread: Optional[str] = None
    resilientwallbasestandard: Optional[str] = None
    style_classification: Optional[str] = None
    floorscore: Optional[str] = None
    wear_layer: Optional[str] = None
    finish: Optional[str] = None
    surface_profile: Optional[str] = None
    recommended_adhesive: Optional[str] = None
    static_load: Optional[str] = None
    squareness: Optional[str] = None
    thickness: Optional[str] = None
    size_and_tolerance: Optional[str] = None
    flexibility: Optional[str] = None
    dimensional_stability: Optional[str] = None
    residual_indentation: Optional[str] = None
    static_coefficient_of_friction: Optional[str] = None
    totalrecycledcontent: Optional[float] = None
    virginvinyl: Optional[str] = None
    certification_detail: Optional[str] = None
    embodied_carbon: Optional[float] = None
    beyond_carbon_neutral: Optional[float] = None
    installationmethod: Optional[str] = None
    csi_master_formatname: Optional[str] = None
    csi_master_formatnumber: Optional[str] = None
    edge_treatment: Optional[str] = None
    environmentalproductdeclaration: Optional[str] = None
    soil_release_technology: Optional[str] = None
    protective_finishes: Optional[str] = None
    carbon_handprint: Optional[float] = None
    material_health: Optional[str] = None
    mindclick_rating: Optional[str] = None
    commercial_initiative: Optional[str] = None
    warranty_link: Optional[str] = None
    installation_link: Optional[str] = None
    care_link: Optional[str] = None
    install_method: Optional[str] = None
    color_code: Optional[str] = None
    marketing_color_name: Optional[str] = None
    color_name: Optional[str] = None
    size: Optional[str] = None
    size_description: Optional[str] = None
    backing_code: Optional[str] = None
    backing_description: Optional[str] = None
    marketing_product_group: Optional[str] = None
    dropped: Optional[str] = None
    deleted: Optional[str] = None
    introduction_date: Optional[str] = None
    quickship: Optional[str] = None
    finished_pile_thickness: Optional[str] = None
    alternatestylenumber1: Optional[str] = None
    alternatestylecolor1: Optional[str] = None
    alternatestylenumber2: Optional[str] = None
    alternatestylecolor2: Optional[str] = None
    alternatestylenumber3: Optional[str] = None
    alternatestylecolor3: Optional[str] = None
    alternatestylenumber4: Optional[str] = None
    alternatestylecolor4: Optional[str] = None
    alternatestylenumber5: Optional[str] = None
    alternatestylecolor5: Optional[str] = None
    alternatestylenumber6: Optional[str] = None
    alternatestylecolor6: Optional[str] = None
    alternatestylenumber7: Optional[str] = None
    alternatestylecolor7: Optional[str] = None
    alternatestylenumber8: Optional[str] = None
    alternatestylecolor8: Optional[str] = None
    alternatestylenumber9: Optional[str] = None
    alternatestylecolor9: Optional[str] = None
    alternatestylenumber10: Optional[str] = None
    alternatestylecolor10: Optional[str] = None
    alternatestylenumbercolorimage1: Optional[str] = None
    alternatestylenumbercolorimage2: Optional[str] = None
    alternatestylenumbercolorimage3: Optional[str] = None
    alternatestylenumbercolorimage4: Optional[str] = None
    alternatestylenumbercolorimage5: Optional[str] = None
    alternatestylenumbercolorimage6: Optional[str] = None
    alternatestylenumbercolorimage7: Optional[str] = None
    alternatestylenumbercolorimage8: Optional[str] = None
    alternatestylenumbercolorimage9: Optional[str] = None
    alternatestylenumbercolorimage10: Optional[str] = None
    online_sample_available: Optional[str] = None
    environmental_claims_validation: Optional[float] = None
    tarr: Optional[str] = None
    health_product_declaration: Optional[str] = None
    leed_certification: Optional[str] = None
    ns140: Optional[str] = None
    red_list_free: Optional[str] = None
    living_product_challenge: Optional[str] = None
    take_back_program: Optional[str] = None
    tvoc_range: Optional[str] = None
    mindful_materials: Optional[str] = None
    upc_code: Optional[float] = None
    msrp: Optional[float] = None
    master_number: Optional[str] = None
    master_name: Optional[str] = None
    sales_available: Optional[str] = None
    product_family: Optional[str] = None
    allow_sales_flag: Optional[str] = None
    preorder_flag: Optional[str] = None
    product_classification: Optional[str] = None
    display_name: Optional[str] = None
    display_desc: Optional[str] = None
    declarelabel: Optional[str] = None
    readytoship: Optional[str] = None
    inv_sku: Optional[str] = None
    width: Optional[float] = None
    width_ft: Optional[float] = None
    weight: Optional[float] = None
    size_number: Optional[str] = None
    inv_backing_code: Optional[str] = None
    primary_backing: Optional[str] = None
    secondary_backing: Optional[str] = None
    sqft_per_piece: Optional[float] = None
    sqft_per_carton: Optional[float] = None
    product_avail_readytoship: Optional[str] = None
    product_avail_readytoship_west: Optional[str] = None
    product_avail_quickship: Optional[str] = None
    pounds_per_carton: Optional[float] = None
    color_family: Optional[str] = None
    uom: Optional[str] = None
    pricing_uom: Optional[str] = None
    max_rollsize: Optional[float] = None
    custom_product: Optional[str] = None
    cartons_per_pallet: Optional[float] = None
    color_number: Optional[str] = None
    inventory_color_name: Optional[str] = None
    product_typename: Optional[str] = None
    inv_product_group: Optional[str] = None
    std_roll_length: Optional[float] = None
    yrd_per_roll: Optional[float] = None
    face_weight: Optional[str] = None
    erp_product_category: Optional[str] = None
    inv_sku_product_classification: Optional[str] = None
    inv_sku_display_name: Optional[str] = None
    inv_sku_display_desc: Optional[str] = None
    pattern_number: Optional[str] = None
    inventory_sku_length: Optional[float] = None
    pieces_per_carton: Optional[float] = None
    light_refectancy: Optional[float] = None
    construction: Optional[str] = None
    surface_finishcode: Optional[str] = None
    pile_weight: Optional[str] = None
    total_weight: Optional[float] = None
    weight_density: Optional[str] = None
    stiches_per_inch: Optional[str] = None
    total_thickness: Optional[str] = None
    pattern_repeat: Optional[str] = None
    pattern_repeat_width: Optional[str] = None
    pattern_repeat_length: Optional[str] = None
    durability_rating: Optional[float] = None
    indoor_air_quality: Optional[str] = None
    inventory_style_name: Optional[str] = None
    inv_product_classification: Optional[str] = None
    inv_style_code: Optional[str] = None
    availablesizes: Optional[str] = None
    edgetreatmentlistforrugs: Optional[str] = None
    thumb_image: Optional[str] = None
    roomscene: Optional[str] = None
    specsheet: Optional[str] = None
    collectionbrochure: Optional[str] = None
    warranty: Optional[str] = None
    careandmaintenance: Optional[str] = None
    installation: Optional[str] = None
    available_sizes: Optional[str] = None
    rug_edge_treatment: Optional[str] = None
    installation_pattern: Optional[str] = None
    specify_for_a_cure: Optional[str] = None
    the_waterways_project: Optional[str] = None

    class Config:
        orm_mode = True
